#!/bin/sh

echo "WARNING, This installation will destroy your existing .bashrc file and other dotfiles! \nDo you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) echo 'Aborting.'; exit;;
    [Yy]* ) echo "proceeding with install.";;
    * ) echo 'Aborting.'; exit;; 
esac

echo "COPYING FILES AND CLOBBERING OLD ENVIRONMENT..." 
cp .bashrc ~/.bashrc
cp .xsession ~/.xsession
sudo cp remembercreds /usr/bin/remembercreds
sudo cp forgetcreds /usr/bin/forgetcreds
cp .cdb ~/.cdb
cp .gdbinit ~/.gdbinit
sudo cp diffconfig /usr/bin/diffconfig
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
# curl -L https://git.io/auto-ls > ~/.oh-my-zsh/plugins/auto-ls.zsh
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/plugins/zsh-autosuggestions
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
sudo ~/.fzf/install
chsh -s $(which zsh) #set zsh as default shell
sudo cp .zshrc ~/.zshrc
sudo cp auto-ls.zsh ~/.oh-my-zsh/plugins/
mkdir ~/.config/i3
sudo cp i3-config ~/.config/i3/config
sudo cp ../images/backgrounds/arc_alps.jpeg ~/.config/i3/
# cp bullet-train.zsh-theme ~/.oh-my-zsh/themes/

echo "COPYING FILES... DONE."
