#!/bin/sh

echo "WARNING, This installation will destroy your existing .bashrc file! \nDo you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) echo 'Aborting.'; exit;;
    [Yy]* ) echo "proceeding with install.";;
    * ) echo 'Aborting.'; exit;; 
esac

echo "COPYING FILES AND CLOBBERING OLD ENVIRONMENT..." 
cp .bashrc ~/.bashrc
cp .xsession ~/.xsession
sudo cp remembercreds /usr/bin/remembercreds
sudo cp forgetcreds /usr/bin/forgetcreds
cp .cdb ~/.cdb
cp .gdbinit ~/.gdbinit
sudo cp diffconfig /usr/bin/diffconfig
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
cp bullet-train.zsh-theme ~/.oh-my-zsh/themes/

echo "COPYING FILES... DONE."
