#!/bin/sh
sudo apt update
sudo apt install cmake git gcc g++ python3 python3-pip -y
git clone https://github.com/keystone-engine/keystone.git
cd keystone
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j$(nproc)
sudo make install
cd ../bindings/python
python3 setup.py install
