#!/bin/bash
# George Ornbo (shapeshed) http://shapeshed.com
# License - http://unlicense.org
#
# Fixes a corrupt .zsh_history file

cd ~
mv ~/.zsh_history ~/.zsh_history_bad
strings .zsh_history_bad > .zsh_history
fc -r ~/.zsh_history #IF THIS FAILS TRY WITH -R capital R arg.
rm ~/.zsh_history_bad
